### ISSUE TITLE
好些个大小写不分

### ISSUE THREAD

**Issue by gdchaochao** [SparkYuan/Meizi#1]
楼主啊。提个不算问题的问题。就是我直接down下来的代码，发现很多大小写不分的呢。是我操作姿势不对吗

比如package com.spark.meizi.Utils;（Utils没有大写但里面却是大写的）

**Comment by SparkYuan** [comment]
刚开始文件名起错了，git又对大小写不敏感，所以就导致了这个问题，目前已知有Utils和OnMeiziClickListener这两个文件首字母大小写有问题，我正在找解决办法。。。

**Comment by SparkYuan** [comment]
已修复
