### ISSUE TITLE
打包apk的时候有遇到这个问题吗

### ISSUE THREAD

**Issue by zhdh2008** [SparkYuan/Meizi#4]
Error:Execution failed for task ':app:transformClassesWithJarMergingForWandoujiaDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/objectweb/asm/commons/AdviceAdapter.class
提示AdviceAdapter这个类重复，看代码并没有什么地方引用啊

**Comment by nagaame** [comment]
我这里也是一样
Error:Execution failed for task ':app:transformClassesWithJarMergingForWandoujiaDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/objectweb/asm/tree/AbstractInsnNode.class

**Comment by yclxiao** [comment]
我也是这个错误

**Comment by SparkYuan** [comment]
最近太忙没能及时回复，抱歉。我打包的时候没有遇到这个问题，最近会想办法修复，谢谢大家的关注。

**Comment by SparkYuan** [comment]
是依赖的库内部包有重复导致的这个问题，在app这个module的build.gradle文件里做如下修改
``` gradle
compile (rootProject.ext.realm){
       exclude group: 'org.ow2.asm', module: 'asm'
        exclude group: 'org.ow2.asm', module: 'asm-commons'
        exclude group: 'org.ow2.asm', module: 'asm-tree'
        exclude group: 'org.ow2.asm', module: 'asm-analysis'
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-runtime'
    }
```
