### ISSUE TITLE
你好，我克隆到本地gradle build遇到了问题

### ISSUE THREAD

**Issue by AoMiao** [SparkYuan/Meizi#7]
详细内容是：
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
还是出现了两次，能请问是什么原因吗

**Comment by SparkYuan** [comment]
把jdk版本换成1.7
